version: "3"
services:
  server:
    image: ${IMAGE}
    command: server
    deploy:
      replicas: 1
    networks:
      - webnet
    ports:
      - "8000:8000"
  check:
    image: ${IMAGE}
    environment: 
      NODE: "{{.Node.ID}}"
    command: ["check", "-f=cmd/actuary/mac-default.toml", "-s=http://server:8000/request"]
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  webnet:
    driver: overlay